supported:
  0: grib2_t40_det_stl       # Analysis/forecast, single time level
  1: grib2_t40_eps_stl       # EPS member, single time level
  2: grib2_t40_epsderived_stl    # EPS derived, single time level
  5: grib2_t40_prob_stl      # Probability, single time level
  6: grib2_t40_quantile_stl      # Quantile, single time level
  8: grib2_t40_det_mtl       # Analysis/forecast, multiple time levels
  9: grib2_t40_prob_mtl      # Probability, multiple time levels
  10: grib2_t40_quantile_mtl     # Quantile, multiple time level
  11: grib2_t40_eps_mtl      # EPS member, mutiple time levels
  12: grib2_t40_epsderived_mtl     # EPS derived, multiple time levels
  20: grib2_t40_radar
  31: grib2_t40_satellite
  32: grib2_t40_det_stl_synsat    # Synthetic satellite, analysis/forecast
  33: grib2_t40_eps_stl_synsat    # Synthetic satellite, EPS member
  53: grib2_t40_det_stl_ppart     # Partitioned parameter
  54: grib2_t40_eps_stl_ppart     # Partitioned parameter
    #     Aerosol
  44: grib2_t40_det_stl_aerosol    # single time level
  45: grib2_t40_eps_stl_aerosol    # EPS mem., single time level
  46: grib2_t40_det_mtl_aerosol    # multiple time levels
  47: grib2_t40_eps_mtl_aerosol    # EPS mem., multiple time levels
  48: grib2_t40_det_stl_aerosol_opt    # optical properties, single time level
    # optical properties, EPS mem., single time level
  49: grib2_t40_eps_stl_aerosol_opt
    #     Chem. constituent
  40: grib2_t40_det_stl_chem           # single time level
  41: grib2_t40_eps_stl_chem           # EPS mem., single time level
  40005: grib2_t40_prob_stl_chem          # Probability, single time level
  40006: grib2_t40_quantile_stl_chem      # Quantile, single time level
  40002: grib2_t40_epsderived_stl_chem    # EPS derived, single time level
  42: grib2_t40_det_mtl_chem         # multiple time levels
  43: grib2_t40_eps_mtl_chem         # EPS mem., multiple time levels
  40009: grib2_t40_prob_mtl_chem          # Probability, multiple time levels
  40010: grib2_t40_quantile_mtl_chem      # Quantile, multiple time levels
  40012: grib2_t40_epsderived_mtl_chem    # EPS derived, multiple time levels
    #     Chem. constituent with distribution
  57: grib2_t40_det_stl_chemdist    # single time level
  58: grib2_t40_eps_stl_chemdist    # EPS mem., single time level
  67: grib2_t40_det_mtl_chemdist    # multiple time levels
  68: grib2_t40_eps_mtl_chemdist    # EPS mem., multiple time levels

dependencies:
  grib2_t40_det_stl:
  - parameterCategory
  - parameterNumber
  - typeOfGeneratingProcess
  - generatingProcessIdentifier
  - backgroundGeneratingProcessIdentifier
  - hoursAfterDataCutoff
  - minutesAfterDataCutoff
        # time
  - indicatorOfUnitOfTimeRange
  - forecastTime
        # level
  - typeOfFirstFixedSurface
  - opt: scaleFactorOfFirstFixedSurface
  - opt: scaledValueOfFirstFixedSurface
  - typeOfSecondFixedSurface
  - opt: scaleFactorOfSecondFixedSurface
  - opt: scaledValueOfSecondFixedSurface
  ensemble_forecast:
  - typeOfEnsembleForecast
  - perturbationNumber
  - numberOfForecastsInEnsemble

  grib2_t40_eps_stl:
  - ref: grib2_t40_det_stl
  - ref: ensemble_forecast

  time_interval:
  - yearOfEndOfOverallTimeInterval
  - monthOfEndOfOverallTimeInterval
  - dayOfEndOfOverallTimeInterval
  - hourOfEndOfOverallTimeInterval
  - minuteOfEndOfOverallTimeInterval
  - secondOfEndOfOverallTimeInterval
  - numberOfTimeRange
  - numberOfMissingInStatisticalProcess
  - typeOfStatisticalProcessing
  - typeOfTimeIncrement
  - indicatorOfUnitForTimeRange
  - lengthOfTimeRange
  - indicatorOfUnitForTimeIncrement
  - timeIncrement

  grib2_t40_det_mtl:
  - ref: grib2_t40_det_stl
  - ref: ensemble_forecast
  - ref: time_interval

  derived_forecast:
  - numberOfForecastsInEnsemble
  - derivedForecast

  grib2_t40_epsderived_stl:
  - ref: grib2_t40_det_stl
  - ref: derived_forecast
  probability_forecast:
  - forecastProbabilityNumber
  - totalNumberOfForecastProbabilities
  - probabilityType
  - scaleFactorOfLowerLimit
  - scaledValueOfLowerLimit
  - scaleFactorOfUpperLimit
  - scaledValueOfUpperLimit
  grib2_t40_prob_stl:
  - ref: grib2_t40_det_stl
  - ref: probability_forecast
  grib2_t40_quantile_stl:
  - ref: grib2_t40_det_stl
  - percentileValue
  grib2_t40_prob_mtl:
  - ref: grib2_t40_det_mtl
  - ref: probability_forecast
  grib2_t40_quantile_mtl:
  - ref: grib2_t40_det_stl
  - percentileValue
  - time_interval
  grib2_t40_eps_mtl:
  - ref: grib2_t40_det_stl
  - ref: ensemble_forecast
  - ref: time_interval

  grib2_t40_epsderived_mtl:
  - ref: grib2_t40_det_stl
  - ref: derived_forecast
  - ref: time_interval

  grib2_t40_radar:
  - parameterCategory
  - parameterNumber
  - typeOfGeneratingProcess
  - numberOfRadarSitesUsed
  - indicatorOfUnitOfTimeRange
  - siteLatitude
  - siteLongitude
  - siteElevation
  - siteId
        # TODO duplicated
  - siteId
  - operatingMode
  - reflectivityCalibrationConstant
  - qualityControlIndicator
  - clutterFilterIndicator
  - constantAntennaElevationAngle
  - accumulationInterval
  - referenceReflectivityForEchoTop
  - rangeBinSpacing
  - radialAngularSpacing

  grib2_t40_satellite:
  - parameterCategory
  - parameterNumber
  - typeOfGeneratingProcess

constraints:
- parameterCategory: "!=-1"
- parameterNumber: "!=-1"
