pipeline {
    environment {
       PATH = "$WORKSPACE/micromamba/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup micromamba') {
            steps {
                sh 'curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"'
                sh 'bash Mambaforge-$(uname)-$(uname -m).sh'
                sh 'rm Mambaforge-$(uname)-$(uname -m).sh'
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                mamba activate idpi
                cd idpi/test
                source setup.sh
                export PYTHONPATH=$WORKSPACE/idpi/src
                pytest -s
                '''
            }
        }
    }
}
