pipeline {
    environment {
       PATH = "$WORKSPACE/micromamba/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup micromamba') {
            steps {
                sh 'curl micro.mamba.pm/install.sh | bash'
                sh 'mamba create -f environment.yml'
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                mamba activate idpi
                cd idpi/test
                source setup.sh
                export PYTHONPATH=$WORKSPACE/idpi/src
                pytest -s
                '''
            }
        }
    }
}
