pipeline {
    environment {
       PATH = "$WORKSPACE/conda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup micromamba') {
            steps {
                sh 'wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"'
                sh 'bash Mambaforge.sh -b -p "${WORKSPACE}/conda"'
                sh 'rm Mambaforge.sh'
                sh 'mamba create -f environment.yml'
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source "$WORKSPACE/conda/etc/profile.d/conda.sh"
                source $WORKSPACE/conda/etc/profile.d/mamba.sh
                mamba activate idpi
                cd idpi/test
                source setup.sh
                export PYTHONPATH=$WORKSPACE/idpi/src
                pytest -s
                '''
            }
        }
    }
}
