name: Formatting & compliance

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
    - name: Create env from unpinned reqs
      run: |
        conda create -n idpi_env
        conda install -n idpi_env -c conda-forge mamba
        conda run -n idpi_env mamba env  update -n idpi_env --file environment_dev.yml
    - name: Install pre-commit hooks
      run: |
        conda run --name idpi_env pre-commit install-hooks
    - name: Run pre-commit hooks
      run: |
        conda run --name idpi_env pre-commit run --all-files
