name: Formatting & compliance

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        channel-priority: flexible
        show-channel-urls: true
        use-mamba: true
    - name: Create env from unpinned reqs
      run: |
        conda env create -f environment_dev.yml
    - name: Install pre-commit hooks
      run: |
        conda run --name idpi_dev pre-commit install-hooks
    - name: Run pre-commit hooks
      run: |
        conda run --name idpi_dev pre-commit run --all-files
